/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.samg.sanote.gui;

/**
 *
 * @author samue
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame(String title) {
        initComponents();
        setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPane = new com.samg.sanote.gui.PrincipalPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(principalPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inici
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        MainFrame mainFrame = new MainFrame("Sanote");
        mainFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.samg.sanote.gui.PrincipalPane principalPane;
    // End of variables declaration//GEN-END:variables
}
